Remove unused widget/tolerance-slider.* / fix DocumentProperties C++20 warnings
https://gitlab.com/inkscape/inkscape/-/merge_requests/5852

commit 8763e108609bc8d90918658b812ebf4b048ec4eb (HEAD -> djb_ToleranceSlider_unused)
Author: Daniel Boles <dboles.src+inkscape@gmail.com>
Date:   Wed Sep 27 14:17:20 2023 +0100

    DocumentProperties—workaround Mac runner Clang bug
    
    This is a bogus warning that was fixed by a Defect Report, but the
    compilers on some runners don't implement that DR.
    
    ```none
    /Users/gitlab/builds/inkscape/inkscape/src/ui/dialog/document-properties.cpp:1441:60: error: reference to local binding 'type' declared in enclosing function 'Inkscape::UI::Dialog::DocumentProperties::build_gridspage'
            btn->signal_clicked().connect([=, this]{ onNewGrid(type); });
                                                               ^
    /Users/gitlab/builds/inkscape/inkscape/src/ui/dialog/document-properties.cpp:1431:30: note: 'type' declared here
        for (auto const &[label, type, icon]: {std::tuple
    ```

commit bfcd8ea63a5990794eb1464b098a5d668f612364
Author: Daniel Boles <dboles.src+inkscape@gmail.com>
Date:   Wed Sep 27 12:55:23 2023 +0100

    DocumentProperties: Fix warnings building on C++20
    
    revealed while building the previous commit.

commit 33bd14c91d8bab3fe9c4011eede89d4c8883a15c
Author: Daniel Boles <dboles.src+inkscape@gmail.com>
Date:   Wed Sep 27 12:52:28 2023 +0100

    Remove unused widget/tolerance-slider.*
    
    They are not used. Let's not migrate them to GTK4.